/* This file was generated by `qmk generate-config-h`. Do not edit or copy.
 */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0003
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION karlk90/yaemk
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER KARLK90
#endif // MANUFACTURER

#ifndef MOUSEKEY_DELAY
#   define MOUSEKEY_DELAY 0
#endif // MOUSEKEY_DELAY

#ifndef MOUSEKEY_INTERVAL
#   define MOUSEKEY_INTERVAL 16
#endif // MOUSEKEY_INTERVAL

#ifndef MOUSEKEY_MAX_SPEED
#   define MOUSEKEY_MAX_SPEED 6
#endif // MOUSEKEY_MAX_SPEED

#ifndef MOUSEKEY_TIME_TO_MAX
#   define MOUSEKEY_TIME_TO_MAX 64
#endif // MOUSEKEY_TIME_TO_MAX

#ifndef MOUSEKEY_WHEEL_DELAY
#   define MOUSEKEY_WHEEL_DELAY 0
#endif // MOUSEKEY_WHEEL_DELAY

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN A10
#endif // RGB_DI_PIN

#ifndef PRODUCT
#   define PRODUCT karlk90/yaemk
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x5941
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x4B4B
#endif // VENDOR_ID

#ifndef QMK_KEYS_PER_SCAN
#   define QMK_KEYS_PER_SCAN 8
#endif // QMK_KEYS_PER_SCAN

#ifndef TAP_CODE_DELAY
#   define TAP_CODE_DELAY 16
#endif // TAP_CODE_DELAY

#ifndef TAPPING_TERM
#   define TAPPING_TERM 160
#endif // TAPPING_TERM

#ifndef TAPPING_TOGGLE
#   define TAPPING_TOGGLE 2
#endif // TAPPING_TOGGLE

#ifndef USB_POLLING_INTERVAL_MS
#   define USB_POLLING_INTERVAL_MS 1
#endif // USB_POLLING_INTERVAL_MS

#ifndef MATRIX_COLS
#   define MATRIX_COLS 8
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { B15, B14, B13, B2, B1, B0, A7, A2 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 5
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { A8, B12, A6, A5, A1 }
#endif // MATRIX_ROW_PINS
